#!/bin/bash

# Set the content type to HTML
echo "Content-type: text/html"
echo ""


# Get the value of the "name" parameter from the URL
HOST=$(echo "$QUERY_STRING" | sed -n 's/^.*HOST=\([^&]*\).*$/\1/p' | sed "s/%20/ /g")
PORT=$(echo "$QUERY_STRING" | sed -n 's/^.*PORT=\([^&]*\).*$/\1/p' | sed "s/%20/ /g")
USER=$(echo "$QUERY_STRING" | sed -n 's/^.*USER=\([^&]*\).*$/\1/p' | sed "s/%20/ /g")
PASS=$(echo "$QUERY_STRING" | sed -n 's/^.*PASS=\([^&]*\).*$/\1/p' | sed "s/%20/ /g")
NAME=$(echo "$QUERY_STRING" | sed -n 's/^.*NAME=\([^&]*\).*$/\1/p' | sed "s/%20/ /g")
ID=$(echo "$QUERY_STRING" | sed -n 's/^.*ID=\([^&]*\).*$/\1/p' | sed "s/%20/ /g")

# Output the HTML document
echo "<html>"
echo "<head>"
echo "<title>Receiver Error Log</title>"
echo "</head>"
echo "<body>"
echo "$NAME ($HOST:$PORT)<br/>"
echo "Clearing<br/>"
echo "<pre>"
#echo ./ErrorLogs.py $HOST $PORT $USER $PASS $NAME --View
./ErrorLogs.py $HOST $PORT $USER $PASS $NAME --View --Clear
./Status_Update.py $ID 2>&1
echo "</pre>"
echo "</body>"
echo "</html>"
